[package]
name = "dalek-rangeproofs"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]

[dependencies]
sha2 = "0.4"
rand = "0.3"

[dependencies.curve25519-dalek]
features = ["yolocrypto", "nightly"]
version = "0.6"

[replace]
"curve25519-dalek:0.6.0" = { git= 'https://github.com/hdevalence/curve25519-dalek', branch = 'feature/operator_scalar_mult_r2' }
